### ISSUE TITLE
Failed to add featurecollection layer to config.json 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#36]
I've started testing a THREE-less, geojson oriented grid (based on @andredaa's work). I could not render a `featurecollection` layer (which is the type of layer the grid needs) when putting it into `config.json`. I'm not sure if this is due to how I spawn the layer or something else: 
https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/3426fcdc7b7d1ad02e38809fea3824799cb6e876

**Comment by RELNO** [comment]
Specifically, I was trying to display this Geojson: https://raw.githubusercontent.com/andredaa/city_io_to_geojson/2ae272d5892724ff82f071299fb2746425e08069/resulting_jsons/example_grasbrook.json

**Comment by andredaa** [comment]
Could you contact Jan on this issue, Till is on holidays and I have no clue
how to solve this.

**Comment by janbehrens** [comment]
There seem to be issues with the test layer:

```
Error: layers.test: missing required property "source"
    at Object.tn [as emitValidationErrors] (http://localhost:4200/vendor.js:143663:118578)
    at Pe (http://localhost:4200/vendor.js:143667:98433)
    at i._validate (http://localhost:4200/vendor.js:143667:117000)
    at i.addLayer (http://localhost:4200/vendor.js:143667:107275)
    at r.addLayer (http://localhost:4200/vendor.js:143667:280083)
    at BasemapComponent.push../src/app/basemap/basemap.component.ts.BasemapComponent.toggleLayer (http://localhost:4200/main.js:386:30)
    at Object.eval [as handleEvent] (ng:///AppModule/BasemapComponent.ngfactory.js:17:27)
    at handleEvent (http://localhost:4200/vendor.js:84364:41)
    at callWithDebugContext (http://localhost:4200/vendor.js:85434:25)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:4200/vendor.js:85161:12)
```

```
Error: layers.test.type: expected one of [fill, line, symbol, circle, heatmap, fill-extrusion, raster, hillshade, background], "geojson" found
    at Object.tn [as emitValidationErrors] (http://localhost:4200/vendor.js:143663:118578)
    at Pe (http://localhost:4200/vendor.js:143667:98433)
    at i._validate (http://localhost:4200/vendor.js:143667:117000)
    at i.addLayer (http://localhost:4200/vendor.js:143667:107275)
    at r.addLayer (http://localhost:4200/vendor.js:143667:280083)
    at BasemapComponent.push../src/app/basemap/basemap.component.ts.BasemapComponent.toggleLayer (http://localhost:4200/main.js:386:30)
    at Object.eval [as handleEvent] (ng:///AppModule/BasemapComponent.ngfactory.js:17:27)
    at handleEvent (http://localhost:4200/vendor.js:84364:41)
    at callWithDebugContext (http://localhost:4200/vendor.js:85434:25)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:4200/vendor.js:85161:12)
```

**Comment by RELNO** [comment]
Thanks @janbehrens  -- As `test` is a `FeatureCollection` layer, it's not clear to me how it should be loaded, this is what we currently have: 

```
    {
      "id": "test",
      "displayName": "test",
      "showInLayerList": true,
      "metadata": "",
      "source": {
        "type": "FeatureCollection",
        "data": {
          "features": [
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [10.011248588562012, 53.535869680557994],
                    [10.006914138793945, 53.53668584621217],
                    [10.007944107055664, 53.53163556873303],
                    [10.014681816101074, 53.53217123277784],
                    [10.015325546264648, 53.53553810876703],
                    [10.011248588562012, 53.535869680557994]
                  ]
                ]
              }
            },
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [10.01901626586914, 53.533115005323005],
                    [10.011119842529297, 53.51969615469332],
                    [10.035839080810547, 53.52163526278576],
                    [10.03326416015625, 53.533115005323005],
                    [10.01901626586914, 53.533115005323005]
                  ]
                ]
              }
            }
          ],
          "type": "FeatureCollection"
        }
      }
    }
```

however it returns:
<img width="486" alt="Screen Shot 2019-06-03 at 10 22 39" src="https://user-images.githubusercontent.com/14296774/58809236-8c589300-85e9-11e9-9722-c7bc5b7b60f9.png">

I was attempting to follow this: https://macwright.org/2015/03/23/geojson-second-bite.html#featurecollection but no luck there

**Comment by janbehrens** [comment]
`source.type` needs to be `"geojson"`, and `layer.type` is missing. This works for me:

```
    {
      "id": "test",
      "displayName": "test",
      "showInLayerList": true,
      "metadata": "",
      "type": "fill",
      "source": {
        "type": "geojson",
        "data": {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [10.011248588562012, 53.535869680557994],
                    [10.006914138793945, 53.53668584621217],
                    [10.007944107055664, 53.53163556873303],
                    [10.014681816101074, 53.53217123277784],
                    [10.015325546264648, 53.53553810876703],
                    [10.011248588562012, 53.535869680557994]
                  ]
                ]
              }
            },
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [10.01901626586914, 53.533115005323005],
                    [10.011119842529297, 53.51969615469332],
                    [10.035839080810547, 53.52163526278576],
                    [10.03326416015625, 53.533115005323005],
                    [10.01901626586914, 53.533115005323005]
                  ]
                ]
              }
            }
          ]
        }
      }
    }
```

See also: https://docs.mapbox.com/mapbox-gl-js/example/multiple-geometries/

**Comment by RELNO** [comment]
@janbehrens great, thanks for catching it -- since my `test` layer was a baseline attempt to test @andredaa noise layer, I think there is some mismatch in the way the noise [example](https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/36#issuecomment-495269814) is formated, but couldn't find exactly where.

**Comment by janbehrens** [comment]
That example GeoJSON is invalid. Accorindg to http://geojsonlint.com/,

```
Line 5: Polygons and MultiPolygons should follow the right-hand rule
Line 42: Polygons and MultiPolygons should follow the right-hand rule
Line 79: Polygons and MultiPolygons should follow the right-hand rule
```
... and so on.

**Comment by RELNO** [comment]
> That example GeoJSON is invalid. 

@andredaa please take a look. @janbehrens thanks!

**Comment by RELNO** [comment]
@andredaa after converting your json here: https://mapster.me/right-hand-rule-geojson-fixer/ grid renders well:
<img width="585" alt="Screen Shot 2019-06-03 at 14 11 56" src="https://user-images.githubusercontent.com/14296774/58824266-a86c2c80-8609-11e9-92be-2268eae068ec.png">

Also note you've a gap in color definition so #{spacebar}XXXX should be #XXXXX

**Comment by andredaa** [comment]
Hello everyone, 
sorry for the late reply - I was on holiday. 
Could you try with this new example: https://github.com/andredaa/city_io_to_geojson/blob/7a2dcbb377c0efb4b1a03626b70e531719ae655d/resulting_jsons/example_grasbrook.json

it works in the geoJson linter .

Ironically I tried many libraries to fix the right hand rule, with led to new problems, etc. 
Then I looked up what the right-hand-rule actually means (put your coordinates in an anti-clockwise order) , and the fix was as easy as this:
 https://github.com/andredaa/city_io_to_geojson/commit/ec383baef90ed83ab38c6da1fccb66bb7c290d20#diff-bb9b63c622e238dd5dfdd713c078396b

**Comment by andredaa** [comment]
If everything works I could create a repo in the github.com/CityScope space

**Comment by RELNO** [comment]
> If everything works I could create a repo in the github.com/CityScope space

Thanks @andredaa  -- as this is a core feature of cityIO, I'd suggest pulling into cityIO main repo.

**Comment by RELNO** [comment]
Closing for now given https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/411ece596f679e6046e60e2a18c580ccae548794
